services:
  azuracast:
    image: ghcr.io/azuracast/azuracast:latest
    container_name: usalb-radio-24
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      AZURACAST_HTTP_PORT: "80"
      AZURACAST_HTTPS_PORT: "443"
    volumes:
      - azuracast_station_data:/var/azuracast

volumes:
  azuracast_station_data:
